'use strict';
const fs = require('fs');
const path = require('path');
const assert = require('assert');
const root = path.resolve(__dirname, '..');
const env = JSON.parse(fs.readFileSync(path.join(root, 'data/direction/directional_resource_envelope.json'), 'utf8').replace(/^\uFEFF/, ''));
const workload = JSON.parse(fs.readFileSync(path.join(root, 'data/direction/directional_workload_baseline.json'), 'utf8').replace(/^\uFEFF/, ''));
const score = JSON.parse(fs.readFileSync(path.join(root, 'data/direction/directional_tps_scorecard.json'), 'utf8').replace(/^\uFEFF/, ''));
const register = JSON.parse(fs.readFileSync(path.join(root, 'data/governance/candidate_register.json'), 'utf8').replace(/^\uFEFF/, ''));
const report = fs.readFileSync(path.join(root, 'reports/direction/stage_a_directional_run_20260921.md'), 'utf8');
assert.strictEqual(env.stage, 'direction');
assert.strictEqual(env.models.length, 3);
assert.strictEqual(env.packageEnvelope.areaConservation, true);
assert.strictEqual(workload.models.find(item => item.modelId === 'K3').status, 'CALIBRATED_DIRECTIONAL_BASELINE');
assert.strictEqual(score.candidateCount, 36);
assert.strictEqual(score.selectedCandidateIds.length, 3);

assert.strictEqual(score.candidateSummaries.length, 12);
assert(score.candidateSummaries.every(item => item.accountedModelCount === 3));
assert(score.candidateSummaries.every(item => item.rankingEligible === true));
assert.strictEqual(score.dGate.areaConservation, true);
assert.strictEqual(score.dGate.threeModelRowsAccounted, true);
assert.strictEqual(score.dGate.threeModelComparable, true);
assert.strictEqual(score.dGate.sensitivitySweep, true);
assert.strictEqual(score.dGate.decision, 'PASS');
assert.strictEqual(register.decisionState, 'D_GATE_PASSED');
assert.strictEqual(register.formalSelectedCandidates.length, 3);
assert(report.includes('D-Gate'));
console.log('PASS stage A directional run: base-unit workload, candidate aggregation and formal candidate aggregation and D-Gate closure recorded');
