'use strict';
const assert = require('assert');
const fs = require('fs');
const path = require('path');
const root = path.resolve(__dirname, '..');
const status = JSON.parse(fs.readFileSync(path.join(root, 'data/governance/gate_status.json'), 'utf8').replace(/^\uFEFF/, ''));
const register = JSON.parse(fs.readFileSync(path.join(root, 'data/governance/candidate_register.json'), 'utf8').replace(/^\uFEFF/, ''));
assert.strictEqual(register.decisionState, 'D_GATE_PASSED');
assert.strictEqual(register.formalSelectedCandidates.length, 3);
assert.strictEqual(status.directionGate.decision, 'PASS');
assert.strictEqual(status.directionGate.threeModelRowsAccounted, true);
assert.strictEqual(status.directionGate.threeModelComparable, true);
assert.strictEqual(status.quantificationGate.exploratoryOnly, true);
assert.strictEqual(status.quantificationGate.provenanceComplete, true);
assert.strictEqual(status.quantificationGate.all18SlotsAccounted, true);
assert.strictEqual(status.quantificationGate.observationMatrixCompleteOrBlocked, false);
assert.strictEqual(status.quantificationGate.decision, 'BLOCKED_BY_D_GATE_MANIFEST_EVENT_MODEL_AND_PROVENANCE');
console.log('PASS independent architecture gate validator: D-Gate planning pass; Q-Gate rejects synthetic evidence');
