'use strict';
const assert = require('assert');
const fs = require('fs');
const path = require('path');
const root = path.resolve(__dirname, '..');
const matrix = JSON.parse(fs.readFileSync(path.join(root, 'data/workload/tps_observation_matrix.json'), 'utf8'));
const casesDoc = JSON.parse(fs.readFileSync(path.join(root, 'data/workload/multi_model_tp_matrix.json'), 'utf8'));
const cases = casesDoc.cases;
assert.strictEqual(matrix.schemaVersion, 'tps-observation-matrix-v0.1');
assert.strictEqual(matrix.status, 'PLANNING_ESTIMATES_COMPLETE');
assert.strictEqual(matrix.metric.id, 'decode_tps_per_user');
assert.strictEqual(matrix.metric.unit, 'tokens/s/user');
assert.strictEqual(matrix.metric.targetTpsPerUser, 1000);
assert.strictEqual(matrix.metric.architectureGateTpsPerUser, 1050);
assert.strictEqual(matrix.observations.length, 18);
assert.deepStrictEqual(matrix.requiredCoverage.models, ['K3', 'GLM-5.2', 'DeepSeek-V4-Pro']);
assert.deepStrictEqual(matrix.requiredCoverage.tp, [8, 16, 32]);
assert.deepStrictEqual(matrix.requiredCoverage.mcProfiles, ['MC320', 'MC640']);
for (const observation of matrix.observations) {
  assert(matrix.requiredCoverage.models.includes(observation.modelId));
  assert(matrix.requiredCoverage.tp.includes(observation.tp));
  assert(matrix.requiredCoverage.mcProfiles.includes(observation.mcProfile));
  assert.strictEqual(observation.metric, matrix.metric.id);
  assert.strictEqual(observation.unit, matrix.metric.unit);
  assert(cases.some(testCase => testCase.caseId === observation.caseId), `${observation.observationId}: missing test case`);
  assert.strictEqual(observation.status, 'PLANNING_ESTIMATE');
  assert.strictEqual(observation.physicalProfile, 'P0');
  assert(Number.isFinite(observation.tpsPerUser) && observation.tpsPerUser > 0);
  assert(Number.isFinite(observation.rawLatencyUsPerToken) && observation.rawLatencyUsPerToken > 0);
  assert(Number.isFinite(observation.e2eLatencyUsPerToken) && observation.e2eLatencyUsPerToken > 0);
  assert(observation.source);
  assert(observation.sourceSelector);
  assert(observation.manifestHash);
  assert(observation.runId);
  assert.strictEqual(observation.blocker, null);
}
const k3Mc320 = matrix.observations.find(o => o.observationId === 'K3-TP32-DECODE-1M-MC320');
const k3Mc640 = matrix.observations.find(o => o.observationId === 'K3-TP32-DECODE-1M-MC640');
assert(k3Mc320.tpsPerUser < matrix.metric.targetTpsPerUser);
assert(k3Mc640.tpsPerUser < matrix.metric.targetTpsPerUser);
assert.notStrictEqual(k3Mc320.tpsPerUser, k3Mc640.tpsPerUser);
assert.strictEqual(matrix.currentCoverage.modelObserved, 0);
assert.strictEqual(matrix.currentCoverage.siliconObserved, 0);
assert.strictEqual(matrix.currentCoverage.pendingModelRun, 18);
assert.strictEqual(matrix.currentCoverage.planningPercentComplete, 100);
console.log('PASS TPS matrix: 18 planning estimates, zero validated observations');
