'use strict';
const assert = require('assert');
const fs = require('fs');
const path = require('path');
const IDS = require('../models/planning/run_ids');
const root = path.resolve(__dirname, '..');
const read = relativePath => JSON.parse(fs.readFileSync(path.join(root, relativePath), 'utf8').replace(/^﻿/, ''));
const detail = read('data/detailed/detailed_architecture_run.json');
const gate = read('data/governance/gate_status.json');
const replay = read('data/detailed/formal_event_replay.json');
const register = read('data/governance/candidate_register.json');
const matrix = read('data/workload/tps_observation_matrix.json');
const report = fs.readFileSync(path.join(root, IDS.stageBReport), 'utf8');
assert.strictEqual(detail.runId, IDS.stageBRunId);
assert.strictEqual(detail.stage, 'quantification');
assert.strictEqual(detail.runMode, 'PLANNING_QUANTIFICATION');
assert.strictEqual(detail.agentId, 'Q1-Q9-orchestrator');
// Candidates come from the register, never from the runner.
assert.deepStrictEqual(detail.selectedCandidates, register.formalSelectedCandidates);
assert.strictEqual(detail.candidateSelection.source, 'data/governance/candidate_register.json');
assert.strictEqual(detail.candidateSelection.formal, true);
assert.strictEqual(detail.candidateSelection.exploratory, false);
assert.strictEqual(detail.candidateSelection.decision, register.decisionState);
assert.deepStrictEqual(detail.manifestStatus, {K3: 'UNVERIFIED_PLANNING_MANIFEST', 'GLM-5.2': 'UNVERIFIED_PLANNING_MANIFEST', 'DeepSeek-V4-Pro': 'UNVERIFIED_PLANNING_MANIFEST'});
assert.strictEqual(detail.operatorLedger.length, 180);
assert.deepStrictEqual([...new Set(detail.operatorLedger.map(row => row.modelId))].sort(), ['DeepSeek-V4-Pro', 'GLM-5.2', 'K3']);
assert.deepStrictEqual([...new Set(detail.operatorLedger.map(row => row.physicalProfile))].sort(), ['P0', 'P1']);
assert.deepStrictEqual([...new Set(detail.operatorLedger.map(row => row.mcProfile))].sort(), ['MC320', 'MC640']);
assert.deepStrictEqual([...new Set(detail.operatorLedger.map(row => row.tp))].sort((a, b) => a - b), [8, 16, 32]);
for (const row of detail.operatorLedger) {
  assert(Number.isFinite(row.arithmeticIntensity) && row.arithmeticIntensity > 0);
  assert(Number.isFinite(row.ridgePoint) && row.ridgePoint > 0);
  assert(['bandwidth', 'compute'].includes(row.rooflineBound));
  assert(Number.isFinite(row.requiredPeakFlops) && row.requiredPeakFlops > 0);
  assert(Number.isFinite(row.availablePeakFlops) && row.availablePeakFlops > 0);
  assert(Number.isFinite(row.requiredToAvailableRatio) && row.requiredToAvailableRatio > 0);
  assert(Number.isFinite(row.requiredMemoryBandwidth) && row.requiredMemoryBandwidth > 0);
  assert(Number.isFinite(row.availableMemoryBandwidth) && row.availableMemoryBandwidth > 0);
  assert(Number.isFinite(row.requiredToAvailableBandwidthRatio) && row.requiredToAvailableBandwidthRatio > 0);
  assert(row.bytes && Number.isFinite(row.bytes.total) && row.bytes.total > 0);
  assert(row.workloadStatus, 'ledger rows must carry the workload provenance status');
}
// P0 and P1 ledger rows for the same operator must use different peak capacity.
const p0 = detail.operatorLedger.find(r => r.physicalProfile === 'P0' && r.modelId === 'K3' && r.tp === 32 && r.mcProfile === 'MC640' && r.coreClass === 'L');
const p1 = detail.operatorLedger.find(r => r.physicalProfile === 'P1' && r.modelId === 'K3' && r.tp === 32 && r.mcProfile === 'MC640' && r.coreClass === 'L');
assert.notStrictEqual(p0.availablePeakFlops, p1.availablePeakFlops);
assert.strictEqual(detail.blockedCases.length, 0);
assert.strictEqual(detail.summary.length, 3);
assert.strictEqual(detail.sizing.targetTpsPerUser, 1000);
assert.strictEqual(detail.sizing.utilizationAssumption, 0.6);
assert.strictEqual(detail.sizing.dutyCycleAssumption, 0.85);
assert(detail.sizing.availableResources.P0.L.peakFlops > 0);
assert(detail.sizing.availableResources.P1.L.peakFlops > 0);
assert.notStrictEqual(detail.sizing.availableResources.P0.L.peakFlops, detail.sizing.availableResources.P1.L.peakFlops);
assert.strictEqual(detail.agentRuns.Q2.status, 'COMPLETE');
assert.strictEqual(detail.agentRuns.Q8.status, 'PLANNING_ONLY');
assert.strictEqual(detail.agentRuns.Q9.status, 'COMPLETE');
assert.strictEqual(detail.observationMatrix.requiredSlots, 18);
assert.strictEqual(detail.observationMatrix.all18SlotsAccounted, true);
assert(detail.provenance.manifestHash);
assert.strictEqual(detail.evidenceKind, 'SYNTHETIC_BOTTLENECK_BOUND');
assert.strictEqual(detail.qGate.provenanceComplete, true);
assert.strictEqual(detail.qGate.p0P1DistinctResources, true);
assert.strictEqual(detail.qGate.observationMatrixCompleteOrBlocked, false);
assert.strictEqual(detail.qGate.decision, 'BLOCKED_BY_D_GATE_MANIFEST_EVENT_MODEL_AND_PROVENANCE');
// Performance acceptance is computed from the slots, not written as a literal.
const target = detail.sizing.targetTpsPerUser;
const gateTps = detail.sizing.architectureGateTpsPerUser;
assert.strictEqual(detail.performanceAcceptance.all18SlotsMeetTarget, matrix.observations.every(o => o.tpsPerUser >= target));
assert.strictEqual(detail.performanceAcceptance.all18SlotsMeetArchitectureGate, matrix.observations.every(o => o.tpsPerUser >= gateTps));
assert(['PERFORMANCE_MISS_REQUIRES_DIRECTION_BACKFLOW', 'SELECTED_CANDIDATES_ABOVE_TARGET_OTHERS_MISS_NOT_VALIDATED', 'PLANNING_BOUND_ABOVE_GATE_NOT_VALIDATED'].includes(detail.performanceAcceptance.status));
assert.strictEqual(replay.eventCount, 720);
assert.strictEqual(replay.events.length, replay.eventCount);
assert(replay.events.every(e => e.status === 'SYNTHETIC_PLACEHOLDER'), 'synthetic events must not be labelled REPLAYED');
assert.strictEqual(gate.quantificationGate.decision, detail.qGate.decision);
assert(report.includes('PLANNING_QUANTIFICATION'));
assert(report.includes(`All 18 slots meet target: **${detail.performanceAcceptance.all18SlotsMeetTarget ? 'yes' : 'no'}**`));
console.log(`PASS Stage B planning: register-driven candidates, distinct P0/P1 capacity, computed acceptance (${detail.performanceAcceptance.status}) and Q-Gate block are explicit`);
