'use strict';
const assert = require('assert');
const fs = require('fs');
const path = require('path');
const root = path.resolve(__dirname, '..');
const read = relativePath => JSON.parse(fs.readFileSync(path.join(root, relativePath), 'utf8').replace(/^\uFEFF/, ''));
const detail = read('data/detailed/detailed_architecture_run.json');
const gate = read('data/governance/gate_status.json');
const replay = read('data/detailed/formal_event_replay.json');
const report = fs.readFileSync(path.join(root, 'reports/detailed/stage_b_formal_run_20260922.md'), 'utf8');
assert(detail.runId);
assert.strictEqual(detail.stage, 'quantification');
assert.strictEqual(detail.runMode, 'PLANNING_QUANTIFICATION');
assert.strictEqual(detail.agentId, 'Q1-Q9-orchestrator');
assert.deepStrictEqual(detail.selectedCandidates, ['P0-7R-balanced-MC640-TP32', 'P0-7R-balanced-MC640-TP16', 'P1-compact-MC640-TP32']);
assert.strictEqual(detail.candidateSelection.formal, true);
assert.strictEqual(detail.candidateSelection.exploratory, false);
assert.strictEqual(detail.candidateSelection.decision, 'D_GATE_PASSED');
assert.deepStrictEqual(detail.manifestStatus, {K3: 'UNVERIFIED_PLANNING_MANIFEST', 'GLM-5.2': 'UNVERIFIED_PLANNING_MANIFEST', 'DeepSeek-V4-Pro': 'UNVERIFIED_PLANNING_MANIFEST'});
assert.strictEqual(detail.operatorLedger.length, 180);
assert.deepStrictEqual([...new Set(detail.operatorLedger.map(row => row.modelId))].sort(), ['DeepSeek-V4-Pro', 'GLM-5.2', 'K3']);
assert.deepStrictEqual([...new Set(detail.operatorLedger.map(row => row.physicalProfile))].sort(), ['P0', 'P1']);
assert.deepStrictEqual([...new Set(detail.operatorLedger.map(row => row.mcProfile))].sort(), ['MC320', 'MC640']);
assert.deepStrictEqual([...new Set(detail.operatorLedger.map(row => row.tp))].sort((a, b) => a - b), [8, 16, 32]);
for (const row of detail.operatorLedger) {
  assert(Number.isFinite(row.arithmeticIntensity) && row.arithmeticIntensity > 0);
  assert(Number.isFinite(row.ridgePoint) && row.ridgePoint > 0);
  assert(['bandwidth', 'compute'].includes(row.rooflineBound));
  assert(Number.isFinite(row.requiredPeakFlops) && row.requiredPeakFlops > 0);
  assert(Number.isFinite(row.availablePeakFlops) && row.availablePeakFlops > 0);
  assert(Number.isFinite(row.requiredToAvailableRatio) && row.requiredToAvailableRatio > 0);
  assert(Number.isFinite(row.requiredMemoryBandwidth) && row.requiredMemoryBandwidth > 0);
  assert(Number.isFinite(row.availableMemoryBandwidth) && row.availableMemoryBandwidth > 0);
  assert(Number.isFinite(row.requiredToAvailableBandwidthRatio) && row.requiredToAvailableBandwidthRatio > 0);
  assert(row.bytes && Number.isFinite(row.bytes.total) && row.bytes.total > 0);
}
assert.strictEqual(detail.blockedCases.length, 0);
assert.strictEqual(detail.summary.length, 3);
assert.strictEqual(detail.sizing.targetTpsPerUser, 1000);
assert.strictEqual(detail.sizing.utilizationAssumption, 0.6);
assert.strictEqual(detail.sizing.dutyCycleAssumption, 0.85);
assert(detail.sizing.availableResources.L.peakFlops > 0);
assert.strictEqual(detail.agentRuns.Q2.status, 'COMPLETE');
assert.strictEqual(detail.agentRuns.Q8.status, 'PLANNING_ONLY');
assert.strictEqual(detail.agentRuns.Q9.status, 'COMPLETE');
assert.strictEqual(detail.observationMatrix.requiredSlots, 18);
assert.strictEqual(detail.observationMatrix.all18SlotsAccounted, true);
assert(detail.provenance.manifestHash);
assert.strictEqual(detail.evidenceKind, 'SYNTHETIC_BOTTLENECK_BOUND');
assert.strictEqual(detail.qGate.provenanceComplete, true);
assert.strictEqual(detail.qGate.observationMatrixCompleteOrBlocked, false);
assert.strictEqual(detail.qGate.decision, 'BLOCKED_BY_D_GATE_MANIFEST_EVENT_MODEL_AND_PROVENANCE');
assert.strictEqual(detail.performanceAcceptance.status, 'PERFORMANCE_MISS_REQUIRES_DIRECTION_BACKFLOW');
assert.strictEqual(detail.performanceAcceptance.all18SlotsMeetTarget, false);
assert.strictEqual(replay.eventCount, 720);
assert.strictEqual(replay.events.length, replay.eventCount);
assert.strictEqual(gate.quantificationGate.decision, detail.qGate.decision);
assert(report.includes('PLANNING_QUANTIFICATION'));
assert(report.includes('All 18 slots meet target: **no**'));
console.log('PASS Stage B planning: operator coverage, evidence limits and Q-Gate block are explicit');
