'use strict';
const assert = require('assert');
const fs = require('fs');
const path = require('path');
const root = path.resolve(__dirname, '..');
const detail = JSON.parse(fs.readFileSync(path.join(root, 'data/detailed/detailed_architecture_run.json'), 'utf8').replace(/^\uFEFF/, ''));
const gate = JSON.parse(fs.readFileSync(path.join(root, 'data/governance/gate_status.json'), 'utf8').replace(/^\uFEFF/, ''));
const report = fs.readFileSync(path.join(root, 'reports/detailed/stage_b_detailed_run_20260921.md'), 'utf8');
assert(detail.runId);
assert.strictEqual(detail.stage, 'quantification');
assert.strictEqual(detail.runMode, 'EXPLORATORY_AFTER_BLOCKED_D_GATE');
assert.strictEqual(detail.agentId, 'Q1-Q9-orchestrator');
assert.strictEqual(detail.selectedCandidates.length, 3);
assert.deepStrictEqual(detail.selectedCandidates, ['P0-7R-balanced-MC320-TP8', 'P0-7R-balanced-MC320-TP16', 'P0-7R-balanced-MC320-TP32']);
assert.strictEqual(detail.candidateSelection.formal, false);
assert.strictEqual(detail.candidateSelection.exploratory, true);
assert.strictEqual(detail.manifestStatus.K3, 'PLANNING_MANIFEST');
assert.strictEqual(detail.manifestStatus['GLM-5.2'], 'BLOCKED_CONFIG');
assert.strictEqual(detail.manifestStatus['DeepSeek-V4-Pro'], 'BLOCKED_CONFIG');
assert.strictEqual(detail.operatorLedger.length, 15);
assert(detail.operatorLedger.every(row => row.modelId === 'K3'));
assert.deepStrictEqual([...new Set(detail.operatorLedger.map(row => row.tp))].sort((a, b) => a - b), [8, 16, 32]);
assert.deepStrictEqual([...new Set(detail.operatorLedger.map(row => row.physicalProfile))], ['P0']);
assert.deepStrictEqual([...new Set(detail.operatorLedger.map(row => row.mcProfile))], ['MC320']);
for (const row of detail.operatorLedger) {
  assert(Number.isFinite(row.arithmeticIntensity) && row.arithmeticIntensity > 0);
  assert(Number.isFinite(row.ridgePoint) && row.ridgePoint > 0);
  assert(['bandwidth', 'compute'].includes(row.rooflineBound));
  assert(Number.isFinite(row.requiredPeakFlops) && row.requiredPeakFlops > 0);
  assert(Number.isFinite(row.availablePeakFlops) && row.availablePeakFlops > 0);
  assert(Number.isFinite(row.requiredToAvailableRatio) && row.requiredToAvailableRatio > 0);
  assert(Number.isFinite(row.requiredMemoryBandwidth) && row.requiredMemoryBandwidth > 0);
  assert(Number.isFinite(row.availableMemoryBandwidth) && row.availableMemoryBandwidth > 0);
  assert(Number.isFinite(row.requiredToAvailableBandwidthRatio) && row.requiredToAvailableBandwidthRatio > 0);
  assert(row.bytes && Number.isFinite(row.bytes.total) && row.bytes.total > 0);
}
assert.strictEqual(detail.blockedCases.length, 6);
assert.deepStrictEqual([...new Set(detail.blockedCases.map(item => item.modelId))].sort(), ['DeepSeek-V4-Pro', 'GLM-5.2']);
assert.strictEqual(detail.summary.length, 1);
assert.strictEqual(detail.summary[0].modelId, 'K3');
assert(Number.isFinite(detail.summary[0].maxRequiredToAvailableRatio));
assert(Number.isFinite(detail.summary[0].maxRequiredToAvailableBandwidthRatio));
assert.strictEqual(detail.sizing.targetTpsPerUser, 1000);
assert.strictEqual(detail.sizing.utilizationAssumption, 0.6);
assert.strictEqual(detail.sizing.dutyCycleAssumption, 0.85);
assert(detail.sizing.availableResources.L.peakFlops > 0);
assert.strictEqual(detail.agentRuns.Q2.status, 'PLANNING_COMPLETE');
assert.strictEqual(detail.agentRuns.Q8.status, 'BLOCKED_UPSTREAM');
assert.strictEqual(detail.observationMatrix.requiredSlots, 18);
assert.strictEqual(detail.observationMatrix.all18SlotsAccounted, true);
assert.strictEqual(detail.provenance.provenanceComplete, undefined);
assert.strictEqual(detail.qGate.provenanceComplete, false);
assert.strictEqual(detail.qGate.all18SlotsAccounted, true);
assert.strictEqual(detail.qGate.observationMatrixCompleteOrBlocked, false);
assert.strictEqual(detail.qGate.decision, 'BLOCKED_BY_D_GATE_MANIFEST_EVENT_MODEL_AND_PROVENANCE');
assert.strictEqual(gate.quantificationGate.decision, detail.qGate.decision);
assert(report.includes('EXPLORATORY_AFTER_BLOCKED_D_GATE'));
assert(report.includes('Req BW TB/s'));
console.log('PASS stage B exploratory run: K3 Roofline, compute/bandwidth sizing, blocked models and Q-Gate provenance recorded');
