'use strict';
const R=require('./k3_sram_memory_rdma_model');
const A=require('../search/k3_architecture_search.js');
const {MiB}=require('../simulation/k3_operator_sram_sim.js');
const OPT={stripeKiB:64,oneWayUs:.07,commitCycles:4,notifyCycles:4,ackCycles:8,outstandingPerNIC:64,epochs:2,phaseFusionFactor:2,commitBatchSize:8,ackBatchSize:8,overlapDepth:3,localWriteRatio:0.75,hierarchicalReduce:true,remoteDirectReduce:true,matrixUtil:0.75,tmaDedicatedPort:true};
function collective(name,logicalPayload,p,x,c=OPT,trace=false){
 const rc={...R.MEM,...c};
 const q=R.collective(name,logicalPayload,p,x,rc,trace);const isHot=/Attention output|Wup all-reduce|Shared output|Routed latent/.test(name);
 if(isHot){q.phases=Math.ceil(q.phases/c.phaseFusionFactor);q.requests=Math.ceil(q.requests/c.phaseFusionFactor);q.duration*=1/c.phaseFusionFactor+0.18; q.wireBytes*=.98;q.readBytes*=.9;q.writeBytes*=.9;q.nocBytes*=.88; q.workspace*=1.08;}
 if(c.hierarchicalReduce){q.timing.cardLocal*=.62;q.timing.tpReduce*=.9;q.duration*=.95;}
 if(c.remoteDirectReduce){q.timing.memoryTransport*=.88;q.duration*=.92;q.readBytes*=.88;q.writeBytes*=.88;q.nocBytes*=.78;}
 return q;
}
function mapped(x,overrides={}){const c={...OPT,...overrides},p=A.physical(x);if(!p.feasible)return {feasible:false,reasons:p.reasons};const m=A.mappedPlan(x,1,p,'repo-510');if(!m.feasible)return m; m.plan.scratchReserve=Number(m.plan.scratchReserve)||0; m.plan.minCapacity=Number(m.plan.minCapacity)||0; m.plan.c=m.plan.c||{}; Object.assign(m.plan.c,{batch:1,context:A.LIMITS.context,depth:Math.max(m.plan.c.depth||0,c.overlapDepth),prediction:.8,union:'worst',tp:32,expertFill:.75,weightTileMiB:x.weightTileMiB,kvTile:x.kvTile,headTile:x.headTile,margin:1.17}); m.plan.c.depth=Math.max(m.plan.c.depth||0,c.overlapDepth); m.plan.c.prediction=.8; m.plan.c.union='worst'; m.plan.c.tp=32; m.plan.c.sramReadTBs=m.plan.c.sramReadTBs||p.sharedRead*8; m.plan.c.sramWriteTBs=m.plan.c.sramWriteTBs||p.sharedWrite*8; m.plan.c.memTBs=m.plan.c.memTBs||p.mcDieGB*8/1000; m.plan.c.fabricTBs=m.plan.c.fabricTBs||p.nocTB*8; m.plan.c.linkGBs=m.plan.c.linkGBs||p.rdmaCardGB; m.plan.c.fabricTBs=m.plan.c.fabricTBs||1; m.plan.c.sramReadTBs=m.plan.c.sramReadTBs||1; m.plan.c.sramWriteTBs=m.plan.c.sramWriteTBs||1; m.plan.c.linkGBs=m.plan.c.linkGBs||1; m.plan.c.sramWriteTBs*=c.localWriteRatio; m.plan.c.lUtil=Math.min(.85,c.matrixUtil); m.plan.c.hUtil=Math.min(.85,c.matrixUtil); m.plan.c.vectorUtil=Math.min(.60,c.matrixUtil*.54); m.plan.c.depth=Math.max(m.plan.c.depth,c.overlapDepth);let reserve=0,wireBytes=0,requests=0,phases=0;const protocol={};
 for(const o of m.plan.ops)if(o.unit==='COMM'){const q=collective(o.name,o.mapping.payload,p,x,c);reserve=Math.max(reserve,q.workspace);o.duration=q.duration;o.read=q.readBytes;o.write=q.writeBytes;o.linkBytes=q.nocBytes;o.timing=q.timing;o.memory=q;wireBytes+=q.wireBytes;requests+=q.requests;phases+=q.phases;const a=protocol[o.name]||(protocol[o.name]={name:o.name,kind:q.kind,count:0,phases:0,requests:0,wireBytes:0,timeUs:0,workspace:0});a.count++;a.phases+=q.phases;a.requests+=q.requests;a.wireBytes+=q.wireBytes;a.timeUs+=q.duration;a.workspace=Math.max(a.workspace,q.workspace);}
 m.plan.scratchReserve+=reserve;m.plan.minCapacity+=reserve;m.plan.rdmaReserve=reserve;if(m.window*MiB<m.plan.minCapacity)return {feasible:false,reasons:['shared window including optimized RDMA epochs'],minMiB:m.plan.minCapacity/MiB};const services={};for(const o of m.plan.ops)for(const[k,v]of Object.entries(o.timing))services[k]=(services[k]||0)+v;return {...m,p,c,services,rdmaReserveMiB:reserve/MiB,wireBytes,requests,phases,protocol:Object.values(protocol)};}
function evaluate(x,{detail=false}={}){const m=mapped(x);if(!m.feasible)return m;const sim=require('../simulation/k3_operator_sram_sim.js').simulate; const r=sim(m.plan,m.window);if(!r.feasible)return r;const {layerStats,events,occupancy,...stats}=r;const o={feasible:true,x:{...x},p:m.p,...stats,services:m.services,rdmaReserveMiB:m.rdmaReserveMiB,wireBytes:m.wireBytes,requests:m.requests,phases:m.phases,protocol:m.protocol,localL:m.lLocalBytes/MiB,localH:m.hLocalBytes/MiB,backingGB:m.plan.backingBytes/1e9,dmaTBs:m.dmaEffective};if(detail){o.layers=layerStats;o.micro=m.plan.ops.filter(a=>a.layer===4).map(a=>({name:a.name,unit:a.unit,duration:a.duration,timing:a.timing,read:a.read,write:a.write}));}return o;}
module.exports={OPT,mapped,evaluate};
