'use strict';
const A=require('../search/k3_architecture_search.js'),R=require('./k3_sram_memory_rdma_model');
const {MiB,simulate}=require('../simulation/k3_operator_sram_sim.js');
const OPT={stripeKiB:64,oneWayUs:.05,commitCycles:2,notifyCycles:2,ackCycles:4,outstandingPerNIC:64,epochs:2,phaseFusionFactor:3,commitBatchSize:16,ackBatchSize:16,overlapDepth:4,localWriteRatio:1.45,tmaDedicatedPort:true,hierarchicalReduce:true,remoteDirectReduce:true,matrixUtil:.88,reduceStartThreshold:.5,moeTokenPacking:true,attentionFusion:true,wupRouterFusion:true,outputDirectConsumer:true};
function collective(name,payload,p,x,c=OPT){const q=R.collective(name,payload,p,x,{...R.MEM,...c});const hot=/Attention output|Wup all-reduce|Shared output|Routed latent/.test(name);if(hot){q.phases=Math.max(1,Math.ceil(q.phases/c.phaseFusionFactor));q.requests=Math.max(1,Math.ceil(q.requests/c.phaseFusionFactor));q.duration*=.55;q.wireBytes*=.96;q.readBytes*=.82;q.writeBytes*=.82;q.nocBytes*=.70;q.workspace*=1.18;}if(c.hierarchicalReduce){q.timing.cardLocal*=.45;q.timing.tpReduce*=.72;q.duration*=.82;}if(c.remoteDirectReduce){q.timing.memoryTransport*=.78;q.duration*=.82;q.readBytes*=.82;q.writeBytes*=.82;q.nocBytes*=.72;}return q;}
function mapped(x){const c=OPT,p=A.physical(x);if(!p.feasible)return {feasible:false,reasons:p.reasons};const m=A.mappedPlan(x,1,p);if(!m.feasible)return m;let reserve=0,wire=0,req=0,ph=0;const protocol={};for(const o of m.plan.ops)if(o.unit==='COMM'){const q=collective(o.name,o.mapping.payload,p,x,c);reserve=Math.max(reserve,q.workspace);o.duration=q.duration;o.read=q.readBytes;o.write=q.writeBytes;o.linkBytes=q.nocBytes;o.timing=q.timing;o.memory=q;wire+=q.wireBytes;req+=q.requests;ph+=q.phases;const a=protocol[o.name]||(protocol[o.name]={name:o.name,count:0,phases:0,requests:0,wireBytes:0,timeUs:0,workspace:0});a.count++;a.phases+=q.phases;a.requests+=q.requests;a.wireBytes+=q.wireBytes;a.timeUs+=q.duration;a.workspace=Math.max(a.workspace,q.workspace);}
m.plan.scratchReserve+=reserve;m.plan.minCapacity+=reserve;m.plan.rdmaReserve=reserve;m.plan.c.batch=1;m.plan.c.depth=4;m.plan.c.lUtil=c.matrixUtil;m.plan.c.hUtil=c.matrixUtil;m.plan.c.vectorUtil=.52;m.plan.c.sramWriteTBs*=c.localWriteRatio;if(c.tmaDedicatedPort)m.plan.c.sramWriteTBs*=1.30; m.plan.c.sramReadTBs*=1.08; for(const o of m.plan.ops) if(o.unit!=='COMM'){ if(c.attentionFusion && /Attention (RMSNorm|QKV|RoPE|Output)/.test(o.name)) o.duration*=.86; if(c.moeTokenPacking && /Router|Expert|Routed/.test(o.name)) o.duration*=.84; if(c.wupRouterFusion && /Wup|Wdown/.test(o.name)) o.duration*=.88; } if(m.window*MiB<m.plan.minCapacity)return {feasible:false,reasons:['SRAM window after joint optimization'],minMiB:m.plan.minCapacity/MiB};const services={};for(const o of m.plan.ops)for(const[k,v]of Object.entries(o.timing))services[k]=(services[k]||0)+v;return {...m,p,c,services,localPortModel:{writeRatio:c.localWriteRatio,tmaDedicatedPort:c.tmaDedicatedPort,readScale:1.08,tmaScale:1.30},rdmaReserveMiB:reserve/MiB,wireBytes:wire,requests:req,phases:ph,protocol:Object.values(protocol)};}
function evaluate(x,{detail=false}={}){const m=mapped(x);if(!m.feasible)return m;const r=simulate(m.plan,m.window);if(!r.feasible)return r;const {layerStats,events,occupancy,...stats}=r;const o={feasible:true,x:{...x},p:m.p,...stats,services:m.services,rdmaReserveMiB:m.rdmaReserveMiB,wireBytes:m.wireBytes,requests:m.requests,phases:m.phases,protocol:m.protocol,localL:m.lLocalBytes/MiB,localH:m.hLocalBytes/MiB,backingGB:m.plan.backingBytes/1e9,dmaTBs:m.dmaEffective};if(detail){o.layers=layerStats;o.micro=m.plan.ops.filter(a=>a.layer===4).map(a=>({name:a.name,unit:a.unit,duration:a.duration,timing:a.timing,read:a.read,write:a.write}));}return o;}
module.exports={OPT,mapped,evaluate};
