const fs=require('fs');
const crypto=require('crypto');
const qualificationPath='data/workload/model_manifest_qualification_matrix.json';
const qualification=JSON.parse(fs.readFileSync(qualificationPath,'utf8').replace(/^\uFEFF/,''));
const RES=require('../models/planning/resource_profiles');
const IDS=require('../models/planning/run_ids');
const matrix=JSON.parse(fs.readFileSync('data/workload/tps_observation_matrix.json','utf8'));
const profileNote=id=>{const c=RES.coreProfiles[id];return `models/planning/resource_profiles.js (${c.lCoresPerDie}L+${c.hCoresPerDie}H, ${c.ghz} GHz; ${c.source})`;};
const contracts={
 schemaVersion:'model-workload-contract-v0.2', status:'BLOCKED_PENDING_VERIFIED_MODEL_SHAPES', ownerTeam:'Model Team', ownerAgents:['MODEL-01','MODEL-02','MODEL-03','MODEL-04'], consumers:['HW-02','HW-03','HW-04','HW-05','SW-01','SW-02','SW-03'], dimensions:{models:['K3','GLM-5.2','DeepSeek-V4-Pro'],tp:[8,16,32],mcProfiles:['MC320','MC640'],physicalProfiles:['P0','P1'],scenarios:['decode-batch1-context1m','prefill-context1m']}, requiredFields:['modelVersion','layerCount','dtype','hiddenSize','attentionShape','expertCount','activeExperts','routingCapacity','kv/index state','MTP behavior','operator shape/layout','FLOP/token','bytes/token','collective bytes'], shapeSources:{K3:'src/core/design_engine.js#MODEL_PRESETS.kimiK3 (engineering preset, single source of truth; not vendor-confirmed)','GLM-5.2':'data/workload/formal_model_manifests.json#/models/1/shape (public HF config.json fields + explicit ASSUMPTION fields for the deployment layout; not vendor-confirmed)','DeepSeek-V4-Pro':'data/workload/formal_model_manifests.json#/models/2/shape (reported fields + explicit ASSUMPTION fields; not vendor-confirmed)'}, evidencePolicy:'All values remain UNVERIFIED until source and shape reconciliation are supplied.', blockers:['GLM-5.2 deployment layout (FP8 KV/index-key bytes, TP mapping, collectives per layer) is ASSUMPTION; shape fields follow the public config.json.','DeepSeek-V4-Pro rests on ASSUMPTION fields (DeepSeek-V3/V3.2 dimensions) pending the vendor config; K3 uses the repository engineering preset.'], outputs:['operator DAG','workload ledger','routing traffic envelope','golden workload trace']
};
Object.assign(contracts,{qualificationMatrix:qualificationPath,qualificationStatus:qualification.status,verifiedFieldCount:qualification.verifiedFieldCount,requiredFieldCount:qualification.requiredFieldCount});
contracts.blockers.push(`Model qualification matrix status: ${qualification.status}; ${qualification.verifiedFieldCount}/${qualification.requiredFieldCount} fields verified.`);
fs.writeFileSync('data/contracts/model_workload_contract.json',JSON.stringify(contracts,null,2)+'\n');
const hw={schemaVersion:'hardware-resource-contract-v0.2',status:'PLANNING_ENVELOPE_PENDING_ACTIVITY_VALIDATION',ownerTeam:'Hardware Team',ownerAgents:['HW-01','HW-02','HW-03','HW-04','HW-05','HW-06'],consumers:['SW-*','MODEL-02','MODEL-03','ARCH-02','ARCH-03'],profiles:{P0:{purpose:'physical primary',resourceStatus:'PARTIAL',coreClassPeakSource:profileNote('P0')},P1:{purpose:'compact executable comparison',resourceStatus:'PARTIAL',coreClassPeakSource:profileNote('P1')}},dimensions:{coreClasses:['L','H','V','INDEXER','REDUCE'],memoryProfiles:['MC320','MC640'],package:'7-reticle / 8 compute die / 16 MC'},requiredFields:['per-core/die/package peak and sustained resource','SRAM bank/port/ECC','MC raw/sustained/effective bandwidth','NoC topology/credit/hop','area/power/thermal/RAS'],blockers:['P0/P1 core-class peaks are distinct planning values; sustained utilization, duty cycle and activity-bound PPA are not independently reconciled.'],outputs:['AI Core spec','memory service model','MC contract','NoC packet contract','PPA/RAS envelope']};
fs.writeFileSync('data/contracts/hardware_resource_contract.json',JSON.stringify(hw,null,2)+'\n');
const sw={schemaVersion:'software-execution-contract-v0.1',status:'PLANNING_OPTIMIZATIONS_NOT_MEASURED',ownerTeam:'Software Team',ownerAgents:['SW-01','SW-02','SW-03','SW-04','SW-05','SW-06','SW-07'],consumers:['ARCH-02','ARCH-03','HW-*','MODEL-05','VV-02'],strategies:['persistent decode','QKV fusion','RoPE+attention fusion','RMSNorm+linear fusion','MoE gate+dispatch fusion','dequant+GEMM fusion','MLP chain fusion','communication-computation overlap','prefetch/double-buffer','MTP acceptance/rollback'],requiredFields:['applicable models/operators','shape/dtype legality','workspace/alias','precision impact','fallback','launch count','resource occupancy','measured or estimated gain','schedule trace'],blockers:['No validated kernel or dependency-aware schedule trace is available.'],outputs:['lowered graph','kernel catalog','fusion legality report','collective overlap schedule','runtime critical path']};
fs.writeFileSync('data/contracts/software_execution_contract.json',JSON.stringify(sw,null,2)+'\n');
const integration={schemaVersion:'integration-manifest-v0.1',status:'BLOCKED_PENDING_THREE_TEAM_ARTIFACTS',requiredTeams:['Hardware Team','Software Team','Model Team'],requiredAgents:['HW-01','HW-02','HW-03','HW-04','HW-05','HW-06','SW-01','SW-02','SW-03','SW-04','SW-05','SW-06','SW-07','MODEL-01','MODEL-02','MODEL-03','MODEL-04','MODEL-05','MODEL-06'],inputs:['data/contracts/model_workload_contract.json','data/contracts/hardware_resource_contract.json','data/contracts/software_execution_contract.json'],hashPolicy:'Every detailed run binds all three contract hashes; mismatch blocks integration.',gatePrerequisites:['verified model shapes','P0/P1 independent resource accounting','dependency-aware timing trace','VV-02 conservation report']};
integration.contractHashes=Object.fromEntries(integration.inputs.map(p=>[p,crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex')]));
integration.generatedAt=qualification.asOf;
fs.writeFileSync('data/contracts/integration_manifest.json',JSON.stringify(integration,null,2)+'\n');
const countStatus=st=>matrix.observations.filter(o=>o.status===st).length;
const evidence={schemaVersion:'timing-evidence-status-v0.1',asOf:IDS.RUN_DATE,current:'CALIBRATED_PLANNING_TOKEN_TIME',validatedSlots:0,planningSlots:countStatus('PLANNING_ESTIMATE'),blockedConfigSlots:countStatus('BLOCKED_CONFIG'),siliconSlots:0,qGate:'BLOCKED',exitCriteria:['validated model workload','memory/packet/kernel/schedule dependency trace','18 validated timed slots','independent VV-02/VV-03 report'],blockers:['Planning token time is calibrated on one K3 detailed point and is not event-timed; synthetic event records do not drive latency.','GLM-5.2 and DeepSeek-V4-Pro apply the K3-fitted factors as a planning ASSUMPTION.']};
fs.writeFileSync('data/verification/timing_evidence_status.json',JSON.stringify(evidence,null,2)+'\n');
