'use strict';
/* Sync the machine-readable P1 baseline from the Final Tuning results.
 *
 * Hand-copied performance numbers drift. This script rewrites ONLY the
 * model-derived fields of docs/design/spec/k3_mc_baseline.json
 * (computeDieCandidate, modelResults, collectiveCount, tauBasis, sramAccounting,
 * acceptance.reason, tpsDesign) and
 * the K3 calibration block of data/direction/directional_workload_baseline.json
 * from data/rdma/k3_rdma_final_tuning_results.json. Human-authored fields
 * (goal, architectureRoute, referenceMemoryCube, bandwidthTiers, tilePlan,
 * card) are preserved.
 *
 * Run after `npm run search:final`: node scripts/sync_baseline_spec.js
 */
const fs = require('fs');
const path = require('path');
const root = path.resolve(__dirname, '..');
const read = p => JSON.parse(fs.readFileSync(path.join(root, p), 'utf8').replace(/^﻿/, ''));
const write = (p, v) => fs.writeFileSync(path.join(root, p), `${JSON.stringify(v, null, 2)}\n`, 'utf8');
const O = require('../src/rdma/k3_rdma_final_tuning_model.js');
const A = require('../src/search/k3_architecture_search.js');
const P = require('../src/search/k3_physical_basis.js');
const T = require('../src/rdma/k3_tps_design_baseline.js');

const results = read('data/rdma/k3_rdma_final_tuning_results.json');
const best = results.search.best;
const x = best.x;
const reference = O.evaluate({...x, mcGBs: 320});
const stretch = O.evaluate({...x, mcGBs: 640});
const replay = O.evaluate(x);
if (!reference.feasible || !stretch.feasible) throw new Error('best candidate must be feasible at MC320 and MC640');
if (!replay.feasible || Math.abs(replay.tps - best.tps) > 1e-7) throw new Error('stored best does not replay from the current model; rerun npm run search:final');
if (x.mcGBs !== 640) console.warn(`warning: search best uses mcGBs=${x.mcGBs}; the MC640 point below is a replay, not the searched optimum`);

const spec = read('docs/design/spec/k3_mc_baseline.json');
const D = A.LIMITS.dies;
spec.version = results.version;
spec.status = 'planning-baseline (P1 compact executable profile; generated by scripts/sync_baseline_spec.js)';
spec.computeDieCandidate = {
  profile: 'P1-compact-executable',
  frequencyGHz: x.ghz,
  lCores: x.nL,
  hCores: x.nH,
  lCore: {tensorEngines: x.lEngines, tensorShape: [x.lRows, x.lCols], vectorLanes: x.vectorLanes, localSramMiB: x.lMiB, tmaEngines: x.tmaEngines, tmaBytesPerCyclePerEngine: x.tmaBytes},
  hCore: {tensorEngines: x.hEngines, tensorShape: [x.hRows, x.hCols], vectorLanes: x.vectorLanes, localSramMiB: x.hMiB, tmaEngines: x.tmaEngines, tmaBytesPerCyclePerEngine: x.tmaBytes},
  sharedSramMiB: x.sharedMiB,
  sharedSramSlices: x.sharedSlices,
  physicalDataSramMiB: stretch.p.totalMiB,
  dataNocBytesPerCyclePerDirection: x.nocBytes,
  abstractNocMesh: [stretch.p.meshSide, stretch.p.meshSide],
  reduceLanes: x.reduceLanes,
  bf16DenseTflops: stretch.p.lTF + stretch.p.hTF,
  vectorTops: stretch.p.vectorTOP,
  estimatedAreaMm2: stretch.p.dieArea,
  estimatedPowerW: stretch.p.diePower,
  estimatedCardPowerW: stretch.p.cardPower,
  sharedPortScalingCost: stretch.p.sharedPortCost || null,
  physicalBasis: {process: P.BASIS.process, areaScale: {...P.PROCESS[P.BASIS.process]}, matrixTFPerMm2: P.BASIS.matrixTFPerMm2, cooling: P.BASIS.cooling, limits: {...P.BASIS.limits}, source: 'src/search/k3_physical_basis.js', note: 'area scaled from the N4-ref TECH coefficients; power, frequency and bandwidth coefficients unchanged; all ASSUMPTION (B-006)'},
  note: 'Area is estimated on the physical basis above. Area and power include the charged shared-SRAM port scaling cost (Final Tuning OPT.chargeSharedPortCost). All coefficients are analytical assumptions pending synthesis/floorplan/IP back-annotation.'
};
// prefetchDepth (1) was a hand-authored leftover; the searched lookahead is optimizedOverlapDepth.
const {prefetchDepth: _staleDepth, ...tilePlanRest} = spec.tilePlan || {};
spec.tilePlan = {
  ...tilePlanRest,
  weightTileMiB: x.weightTileMiB,
  kvTileTokens: x.kvTile,
  kvCacheFormat: O.OPT.kvCache,
  headTile: x.headTile,
  optimizedOverlapDepth: x.depth,
  rdmaStripeKiB: O.OPT.stripeKiB,
  partialReadyThresholds: {attention: O.OPT.partialThresholdAttention, lse: O.OPT.partialThresholdLSE, router: O.OPT.partialThresholdRouter}
};
const point = r => ({
  tpsPerUser: r.tps,
  rawLatencyUs: r.rawUs,
  e2eLatencyUs: r.e2eUs,
  computeUs: r.computeUs,
  commUs: r.commUs,
  dmaWaitUs: r.waitUs,
  commOverlapUs: r.overlapUs,
  tmaFillUs: r.tmaFillUs,
  tmaHiddenUs: r.tmaHiddenUs,
  readBytesPerRankPerToken: r.readBytes,
  effectiveDmaTBsPerCard: r.dmaTBs
});
spec.modelResults = {
  profile: 'P1-compact-executable',
  source: 'data/rdma/k3_rdma_final_tuning_results.json',
  referenceMc320GBs: point(reference),
  stretchMc640GBs: point(stretch)
};

// Collective counting basis. This is a COUNTING choice, not a physical
// optimization: under 'reference-393' the Q/new-KV all-gather and the sampling
// broadcast stay in the DAG as local ops instead of network traffic. Reporting
// a higher TPS on this basis must not be read as a gain.
const byPhase = {};
for (const a of replay.protocol) byPhase[a.name] = a.count;
const collectiveTotal = replay.protocol.reduce((s, a) => s + a.count, 0);
spec.collectiveCount = {
  total: collectiveTotal,
  byPhase,
  countBasis: O.OPT.countBasis,
  referencePageTotal: 393,
  repoBaselineTotal: 510,
  referencePageSource: 'references/k3_1000tps_chip_designs.html:1720',
  reconciliation: 'docs/design/teams/software/SW-05_COLLECTIVE_STRATEGY_REVISION.md#1',
  status: 'accepted 2026-09-25 (B-007); the folded reduction follows the shared-expert compute',
  note: 'The 510->393 difference is 92 folded shared-output reductions plus 24 Q/new-KV all-gathers and 1 sampling broadcast that the reference page does not count; it is not a measured speedup.'
};

// tau basis. SW-05 section 2 found four mutually inconsistent per-collective
// latency defaults on this path. Since 2026-09-25 the published point floors
// every collective at OPT.tauUs (the spec 1.15 us). The ceiling is analytic
// because the simulator asserts raw = compute - tmaHidden + comm + wait - overlap and COMM shares
// the compute slot, except for the data-independent shared experts that run
// under a collective (OPT.commOverlap) and the shared->local fills on the TMA
// lanes (OPT.tmaLane); both are subtracted at their observed values.
const observedNsPerCollective = collectiveTotal ? (replay.commUs * 1000) / collectiveTotal : null;
const specTauUs = 1.15;
if (O.OPT.tauUs !== specTauUs) throw new Error(`OPT.tauUs ${O.OPT.tauUs} differs from the spec tau ${specTauUs}`);
const ceiling = N => 1e6 / ((replay.computeUs - replay.tmaHiddenUs + N * specTauUs - replay.overlapUs) * spec.goal.engineeringMargin);
spec.tauBasis = {
  publishedBasis: 'floor at OPT.tauUs (decision 2026-09-25)',
  tauUs: O.OPT.tauUs,
  oneWayUs: O.OPT.oneWayUs,
  observedNsPerCollective,
  specNsPerCollective: specTauUs * 1000,
  ratioToSpec: observedNsPerCollective ? (specTauUs * 1000) / observedNsPerCollective : null,
  sourcesInRepo: {
    'src/simulation/k3_operator_sram_sim.js#tauUs': 1.15,
    'src/rdma/k3_sram_memory_rdma_model.js#MEM.oneWayUs': 0.10,
    'src/rdma/k3_rdma_final_tuning_model.js#OPT.tauUs (published floor)': O.OPT.tauUs,
  'src/rdma/k3_rdma_final_tuning_model.js#OPT.oneWayUs': O.OPT.oneWayUs,
    'data/rdma/k3_b1_1000_rdma_sram_results.json (2026-09-19 observed)': 0.871
  },
  ceilingTpsByCount: Object.fromEntries([510, 485, 393, 301, 209].map(n => [n, ceiling(n)])),
  overlapUs: replay.overlapUs,
  tmaHiddenUs: replay.tmaHiddenUs,
  note: 'ceiling(N) = 1e6 / ((computeUs - tmaHiddenUs + N x 1.15us - overlapUs) x 1.17), analytic given the simulator conservation identity raw = compute - tmaHidden + comm + wait - overlap, with DMA wait taken as zero; overlapUs is the shared-expert compute hidden under collectives and tmaHiddenUs the shared->local fills hidden on the TMA lanes, both held at their observed values (fewer collectives leave less time to hide fills under, so the ceiling is optimistic). The published point uses the spec tau as a per-collective floor; after the 2026-09-25 attention/small-op mapping (layer PV merge, softmax and epilogue fusion) the 393 ceiling is above 1000 TPS, so the remaining margin is DMA wait, not the collective count.',
  blocker: 'B-008 (tau basis unified at 1.15 us on 2026-09-25; physical derivation still depends on B-004/B-005)',
  adr: 'docs/design/decisions/ADR-0004-collective-tau-basis-and-count-basis.md'
};
spec.sramAccounting = {
  physicalMiBPerDie: stretch.p.totalMiB,
  physicalMiBPerCard: stretch.p.totalMiB * D,
  sharedPhysicalMiBPerCard: x.sharedMiB * D,
  sharedUsableWindowMiBPerCard: stretch.sramMiB,
  simulatedPeakReservedMiBPerCard: stretch.peakReservedMiB,
  note: 'The simulator peak and window are card-aggregate shared-SRAM values, not per-die values. Per-core local SRAM is accounted separately by tile-fit constraints.'
};
spec.acceptance = {
  ...spec.acceptance,
  architectureGateTpsPerUser: 1050,
  currentStatus: stretch.tps >= spec.goal.target ? 'target-met-in-model-only' : 'not-met',
  architectureGateStatus: 'not-met (P1 engineering model; gate requires the selected manufacturable MC route in the detailed tile model)',
  reason: `The best stretch-MC candidate is ${stretch.tps.toFixed(2)} TPS/usr and the reference-compatible 320 GB/s MC point is about ${reference.tps.toFixed(2)} TPS/usr (P1 compact executable profile, engineering model).`
};
// TPS/usr design baseline (docs/design/21_TPS_DESIGN_BASELINE.md, ADR-0005).
spec.tpsDesign = T.build(x, spec.goal.rawLatencyBudgetUs);
write('docs/design/spec/k3_mc_baseline.json', spec);

// Directional workload baseline: the K3 calibration block mirrors the MC320 point.
const baseline = read('data/direction/directional_workload_baseline.json');
const k3 = baseline.models.find(m => m.modelId === 'K3');
// FLOP/token is the detailed plan's own operator FLOP (absorbed MLA attention,
// the same count the tile simulator times), summed over the TP ranks.
const planOps = O.mapped(x).plan.ops;
const opFlops = unit => planOps.filter(o => unit ? o.unit === unit : true).reduce((a, o) => a + (o.flops || 0), 0) * spec.goal.tpCards;
k3.globalFlopsPerToken = opFlops();
k3.globalMemoryBytesPerToken = reference.readBytes * spec.goal.tpCards;
k3.collectiveReference = {...k3.collectiveReference, tp: spec.goal.tpCards, latencyUsPerToken: reference.commUs};
k3.calibration = {
  observedTp: spec.goal.tpCards,
  observedReadBytesPerRank: reference.readBytes,
  observedRawLatencyUs: reference.rawUs,
  observedE2eLatencyUs: reference.e2eUs,
  observedTpsPerUser: reference.tps,
  source: 'data/rdma/k3_rdma_final_tuning_results.json (MC320 replay of search.best)',
  flopDerivation: `sum of operator FLOP in O.mapped(search.best.x).plan x TP${spec.goal.tpCards}: L ${(opFlops('L') / 1e12).toFixed(6)}T, H ${(opFlops('H') / 1e12).toFixed(6)}T (absorbed-MLA QK/PV over the full context), V ${(opFlops('V') / 1e12).toFixed(6)}T`
};
baseline.asOf = results.version.slice(0, 10);
write('data/direction/directional_workload_baseline.json', baseline);

console.log(JSON.stringify({
  version: spec.version,
  mc320: {tps: reference.tps, rawUs: reference.rawUs},
  mc640: {tps: stretch.tps, rawUs: stretch.rawUs},
  dieAreaMm2: stretch.p.dieArea, diePowerW: stretch.p.diePower, cardPowerW: stretch.p.cardPower,
  globalMemoryBytesPerToken: k3.globalMemoryBytesPerToken
}, null, 2));
