'use strict';
/* Sync the machine-readable P1 baseline from the Final Tuning results.
 *
 * Hand-copied performance numbers drift. This script rewrites ONLY the
 * model-derived fields of docs/design/spec/k3_mc_baseline.json
 * (computeDieCandidate, modelResults, sramAccounting, acceptance.reason) and
 * the K3 calibration block of data/direction/directional_workload_baseline.json
 * from data/rdma/k3_rdma_final_tuning_results.json. Human-authored fields
 * (goal, architectureRoute, referenceMemoryCube, bandwidthTiers, tilePlan,
 * card) are preserved.
 *
 * Run after `npm run search:final`: node scripts/sync_baseline_spec.js
 */
const fs = require('fs');
const path = require('path');
const root = path.resolve(__dirname, '..');
const read = p => JSON.parse(fs.readFileSync(path.join(root, p), 'utf8').replace(/^﻿/, ''));
const write = (p, v) => fs.writeFileSync(path.join(root, p), `${JSON.stringify(v, null, 2)}\n`, 'utf8');
const O = require('../src/rdma/k3_rdma_final_tuning_model.js');
const A = require('../src/search/k3_architecture_search.js');
const E = require('../src/core/design_engine.js');

const results = read('data/rdma/k3_rdma_final_tuning_results.json');
const best = results.search.best;
const x = best.x;
const reference = O.evaluate({...x, mcGBs: 320});
const stretch = O.evaluate({...x, mcGBs: 640});
const replay = O.evaluate(x);
if (!reference.feasible || !stretch.feasible) throw new Error('best candidate must be feasible at MC320 and MC640');
if (!replay.feasible || Math.abs(replay.tps - best.tps) > 1e-7) throw new Error('stored best does not replay from the current model; rerun npm run search:final');
if (x.mcGBs !== 640) console.warn(`warning: search best uses mcGBs=${x.mcGBs}; the MC640 point below is a replay, not the searched optimum`);

const spec = read('docs/design/spec/k3_mc_baseline.json');
const D = A.LIMITS.dies;
spec.version = results.version;
spec.status = 'planning-baseline (P1 compact executable profile; generated by scripts/sync_baseline_spec.js)';
spec.computeDieCandidate = {
  profile: 'P1-compact-executable',
  frequencyGHz: x.ghz,
  lCores: x.nL,
  hCores: x.nH,
  lCore: {tensorEngines: x.lEngines, tensorShape: [x.lRows, x.lCols], vectorLanes: x.vectorLanes, localSramMiB: x.lMiB, tmaEngines: x.tmaEngines, tmaBytesPerCyclePerEngine: x.tmaBytes},
  hCore: {tensorEngines: x.hEngines, tensorShape: [x.hRows, x.hCols], vectorLanes: x.vectorLanes, localSramMiB: x.hMiB, tmaEngines: x.tmaEngines, tmaBytesPerCyclePerEngine: x.tmaBytes},
  sharedSramMiB: x.sharedMiB,
  sharedSramSlices: x.sharedSlices,
  physicalDataSramMiB: stretch.p.totalMiB,
  dataNocBytesPerCyclePerDirection: x.nocBytes,
  abstractNocMesh: [stretch.p.meshSide, stretch.p.meshSide],
  reduceLanes: x.reduceLanes,
  bf16DenseTflops: stretch.p.lTF + stretch.p.hTF,
  vectorTops: stretch.p.vectorTOP,
  estimatedAreaMm2: stretch.p.dieArea,
  estimatedPowerW: stretch.p.diePower,
  estimatedCardPowerW: stretch.p.cardPower,
  sharedPortScalingCost: stretch.p.sharedPortCost || null,
  note: 'Area and power include the charged shared-SRAM port scaling cost (Final Tuning OPT.chargeSharedPortCost). All coefficients are analytical assumptions pending synthesis/floorplan/IP back-annotation.'
};
spec.tilePlan = {
  ...spec.tilePlan,
  weightTileMiB: x.weightTileMiB,
  kvTileTokens: x.kvTile,
  headTile: x.headTile,
  optimizedOverlapDepth: O.OPT.overlapDepth,
  rdmaStripeKiB: O.OPT.stripeKiB,
  partialReadyThresholds: {attention: O.OPT.partialThresholdAttention, lse: O.OPT.partialThresholdLSE, router: O.OPT.partialThresholdRouter}
};
const point = r => ({
  tpsPerUser: r.tps,
  rawLatencyUs: r.rawUs,
  e2eLatencyUs: r.e2eUs,
  computeUs: r.computeUs,
  commUs: r.commUs,
  dmaWaitUs: r.waitUs,
  readBytesPerRankPerToken: r.readBytes,
  effectiveDmaTBsPerCard: r.dmaTBs
});
spec.modelResults = {
  profile: 'P1-compact-executable',
  source: 'data/rdma/k3_rdma_final_tuning_results.json',
  referenceMc320GBs: point(reference),
  stretchMc640GBs: point(stretch)
};
spec.sramAccounting = {
  physicalMiBPerDie: stretch.p.totalMiB,
  physicalMiBPerCard: stretch.p.totalMiB * D,
  sharedPhysicalMiBPerCard: x.sharedMiB * D,
  sharedUsableWindowMiBPerCard: stretch.sramMiB,
  simulatedPeakReservedMiBPerCard: stretch.peakReservedMiB,
  note: 'The simulator peak and window are card-aggregate shared-SRAM values, not per-die values. Per-core local SRAM is accounted separately by tile-fit constraints.'
};
spec.acceptance = {
  ...spec.acceptance,
  architectureGateTpsPerUser: 1050,
  currentStatus: stretch.tps >= spec.goal.target ? 'target-met-in-model-only' : 'not-met',
  architectureGateStatus: 'not-met (P1 engineering model; gate requires the selected manufacturable MC route in the detailed tile model)',
  reason: `The best stretch-MC candidate is ${stretch.tps.toFixed(2)} TPS/usr and the reference-compatible 320 GB/s MC point is about ${reference.tps.toFixed(2)} TPS/usr (P1 compact executable profile, engineering model).`
};
write('docs/design/spec/k3_mc_baseline.json', spec);

// Directional workload baseline: the K3 calibration block mirrors the MC320 point.
const baseline = read('data/direction/directional_workload_baseline.json');
const k3 = baseline.models.find(m => m.modelId === 'K3');
const preset = E.MODEL_PRESETS.kimiK3;
const model = E.deriveModel(preset);
const attentionFlops = model.attnFlopsPerToken(spec.goal.contextTokens);
k3.globalFlopsPerToken = 2 * preset.activeParams + attentionFlops;
k3.globalMemoryBytesPerToken = reference.readBytes * spec.goal.tpCards;
k3.collectiveReference = {...k3.collectiveReference, tp: spec.goal.tpCards, latencyUsPerToken: reference.commUs};
k3.calibration = {
  observedTp: spec.goal.tpCards,
  observedReadBytesPerRank: reference.readBytes,
  observedRawLatencyUs: reference.rawUs,
  observedE2eLatencyUs: reference.e2eUs,
  observedTpsPerUser: reference.tps,
  source: 'data/rdma/k3_rdma_final_tuning_results.json (MC320 replay of search.best)',
  flopDerivation: `2 x ${preset.activeParams / 1e9}B active parameters + ${(attentionFlops / 1e12).toFixed(6)}T long-context attention/state FLOP from src/core/design_engine.js`
};
baseline.asOf = results.version.slice(0, 10);
write('data/direction/directional_workload_baseline.json', baseline);

console.log(JSON.stringify({
  version: spec.version,
  mc320: {tps: reference.tps, rawUs: reference.rawUs},
  mc640: {tps: stretch.tps, rawUs: stretch.rawUs},
  dieAreaMm2: stretch.p.dieArea, diePowerW: stretch.p.diePower, cardPowerW: stretch.p.cardPower,
  globalMemoryBytesPerToken: k3.globalMemoryBytesPerToken
}, null, 2));
