'use strict';
const fs=require('fs'); const path=require('path'); const assert=require('assert');
const root=path.resolve(__dirname, '../..');
const doc=fs.readFileSync(path.join(root,'teams/council/docs/18_AGENT_CATALOG_AND_INTERACTION_PROTOCOL.md'),'utf8');
const c=JSON.parse(fs.readFileSync(path.join(root,'teams/council/inputs/agent_catalog_interaction_protocol.json'),'utf8').replace(/^\uFEFF/,''));
assert(doc.includes('3. Agent 角色定义'));
assert(doc.includes('4. 高层设计流程：Agent 交互时序'));
assert(doc.includes('6. 详细设计流程：数据依赖和交互'));
assert.strictEqual(c.agents.direction.length,7);
assert.strictEqual(c.agents.quantification.length,9);
assert.strictEqual(c.interactionRules.maxCandidatesAfterDGate,3);
assert(c.interactionRules.sharedManifestHashAcrossQ2ToQ8);
for(const key of c.interactionRules.artifactEnvelopeRequired) assert(doc.includes(key));
console.log('PASS agent catalog and interaction protocol: roles, contracts, workflows and gates');
