'use strict';
const fs = require('fs');
const path = require('path');
const assert = require('assert');
const root = path.resolve(__dirname, '../..');
const doc = fs.readFileSync(path.join(root, 'teams/council/docs/19_DETAILED_ARCHITECTURE_OPERATING_MODEL.md'), 'utf8');
const readme = fs.readFileSync(path.join(root, 'teams/council/docs/detailed/README.md'), 'utf8');
const model = JSON.parse(fs.readFileSync(path.join(root, 'teams/council/inputs/detailed_architecture_operating_model.json'), 'utf8').replace(/^\uFEFF/, ''));
const stage = JSON.parse(fs.readFileSync(path.join(root, 'teams/council/inputs/architecture_stage_operating_model.json'), 'utf8').replace(/^\uFEFF/, ''));
assert(doc.includes('B0 控制面与候选绑定'));
assert(doc.includes('B1：工作负载、算术强度与资源 sizing'));
assert(doc.includes('B2：物理映射与事件生成'));
assert(doc.includes('B3：执行实现与 PPA'));
assert(doc.includes('B4：系统性能集成'));
assert(doc.includes('B5：验证、Q-Gate 与反馈'));
assert(doc.includes('DIRECTION_BACKFLOW'));
assert(readme.includes('01_Q1_MANIFEST_OPERATOR_SPEC.md'));
assert(readme.includes('09_Q9_VERIFICATION_GATE_SPEC.md'));
assert.deepStrictEqual(model.phases.map(item => item.id), ['B0_CONTROL', 'B1_QUANTIFICATION', 'B2_PHYSICAL_MAPPING', 'B3_EXECUTION_REALIZATION', 'B4_SYSTEM_INTEGRATION', 'B5_VERIFICATION_GATE']);
assert(model.phases.find(item => item.id === 'B2_PHYSICAL_MAPPING').parallel);
assert.deepStrictEqual(model.phases.find(item => item.id === 'B2_PHYSICAL_MAPPING').agents, ['Q3', 'Q4', 'Q5']);
assert(model.feedbackRoutes.some(item => item.decisionType === 'DIRECTION_BACKFLOW' && item.requiresAdr));
assert(stage.detailedOperatingModel);
assert.strictEqual(stage.detailedOperatingModel.machineReadable, 'teams/council/inputs/detailed_architecture_operating_model.json');
console.log('PASS detailed architecture operating model: B0-B5 work packages, parallel event modeling and direction feedback are defined');
