'use strict';
/* Generate out/dashboard/architecture_global_dashboard.html from the current machine artifacts.
 * Run after generate_direction_feedback.js: node integration/pipelines/generate_global_dashboard.js
 */
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const root = path.resolve(__dirname, '../..');
const IDS = require('../planning/run_ids');
const read = p => JSON.parse(fs.readFileSync(path.join(root,p),'utf8').replace(/^\uFEFF/,''));
const mcBaseline = read('teams/hardware/inputs/k3_mc_baseline.json');
const historicalK3 = `${mcBaseline.modelResults.referenceMc320GBs.tpsPerUser.toFixed(2)} / ${mcBaseline.modelResults.stretchMc640GBs.tpsPerUser.toFixed(2)}`;
const sources = ['out/governance/gate_status.json','out/detailed/detailed_architecture_run.json','out/workload/tps_observation_matrix.json','out/direction/sensitivity_sweep.json','out/contracts/model_workload_contract.json','out/contracts/hardware_resource_contract.json','out/contracts/software_execution_contract.json','out/contracts/integration_manifest.json','out/verification/timing_evidence_status.json'];
const [gate,detail,matrix,sweep,modelContract,hardwareContract,softwareContract,integrationContract,evidence] = sources.map(read);
sources.push(modelContract.qualificationMatrix);
const hashes = Object.fromEntries(sources.map(p=>[p,crypto.createHash('sha256').update(fs.readFileSync(path.join(root,p))).digest('hex')]));
const integrationHashesMatch = integrationContract.inputs.every(p => integrationContract.contractHashes && integrationContract.contractHashes[p] === hashes[p]);
const integrationHashMessage = integrationHashesMatch ? 'Contract hashes match; waiting for gate prerequisites' : 'Contract hash mismatch blocks integration';
const esc = s => String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
// Blockers come from the Stage A backflow written by generate_direction_feedback.js.
const {blockers} = read('out/governance/direction_feedback.json');
const range = xs => `${Math.min(...xs).toFixed(0)} – ${Math.max(...xs).toFixed(0)}`;
const tauCell = x => x.tpsPerUserTauSensitivity ? `${range(x.tpsPerUserTauSensitivity.map(t=>t.tpsPerUser))}${x.tp===32?' <b>(TP32)</b>':''}` : '-';
const rows = matrix.observations.map(x=>`<tr><td>${esc(x.modelId)}</td><td>${x.tp}</td><td>${esc(x.mcProfile)}</td><td>${esc(x.physicalProfile)}</td><td>${x.tpsPerUser===null?'BLOCKED_CONFIG':x.tpsPerUser.toFixed(2)}</td><td>${tauCell(x)}</td><td>${x.tpsPerUserShapeRange?`${x.tpsPerUserShapeRange.min.toFixed(0)} – ${x.tpsPerUserShapeRange.max.toFixed(0)}`:'-'}</td><td>${esc(x.boundingOperatorId||'')}</td><td>${esc(x.status)}</td></tr>`).join('');
const cal = detail.tokenTime.calibration;
const dtypeRows = Object.entries(detail.tokenTime.dtypePolicy).map(([m,d])=>`<tr><td>${esc(m)}</td><td>${esc(d.attentionAndDenseProjections)}</td><td>${esc(d.sharedExpert)}</td><td>${esc(d.routerAndLmHead)}</td><td>${esc(d.routedExpert)}</td><td>${esc(d.kvCache)}</td></tr>`).join('');
const checks = (obj)=>Object.entries(obj).filter(([,v])=>typeof v==='boolean').map(([k,v])=>`<tr><td>${esc(k)}</td><td class="${v?'ok':'bad'}">${v?'PASS':'NOT READY'}</td></tr>`).join('');
const html=`<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Architecture Global Dashboard</title><style>
*{box-sizing:border-box}body{margin:0;background:#0b1220;color:#e6edf8;font:15px/1.6 system-ui,"Microsoft YaHei",sans-serif}main{max-width:1400px;margin:auto;padding:28px}h1{font-size:30px}h2{font-size:19px}.muted{color:#a2b4cc}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.cards{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:16px}.panel{background:#142139;border:1px solid #2c405d;border-radius:14px;padding:20px;margin:12px 0;overflow:auto}.value{font-size:27px;font-weight:bold}.ok{color:#67e4b2}.bad{color:#ffb578}.notice{border-left:4px solid #ffb578;padding:14px;background:#322821}table{width:100%;border-collapse:collapse;font-size:13px}td,th{padding:9px;text-align:left;border-bottom:1px solid #30405b}code{overflow-wrap:anywhere}a{color:#73d6fa}li{margin:8px 0}@media(max-width:850px){.grid{grid-template-columns:1fr}.cards{grid-template-columns:repeat(2,1fr)}main{padding:14px}}@media(max-width:450px){.cards{grid-template-columns:1fr}}
</style></head><body><main><p class="muted">K3 / GLM-5.2 / DeepSeek-V4-Pro</p><h1>芯片架构全局看板</h1><p>机器数据快照 · ${esc(detail.runId)} · Gate 评估 ${esc(gate.evaluatedAt)}</p>
<div class="notice"><b>修正此前的 Q-Gate PASS：</b>当前事件是合成规划数据，并未驱动时序计算，不能称为完整 replay 或 fine TPS。D-Gate PASS 仅代表规划比较，不代表架构冻结。供应商未确认配置不标记 FROZEN。</div>
<section class="cards"><div class="panel">目标<div class="value">1000 TPS/usr</div>架构门槛 1050</div><div class="panel">D-Gate · 规划比较<div class="value">${esc(gate.directionGate.decision)}</div>非性能验收</div><div class="panel">Q-Gate · 详细量化<div class="value bad">${gate.quantificationGate.decision==='PASS'?'PASS':'BLOCKED'}</div>缺少有效事件时序</div><div class="panel">规划槽位 / 有效观测<div class="value">${matrix.currentCoverage.planningEstimated || 0} / ${matrix.currentCoverage.modelObserved}</div>silicon ${matrix.currentCoverage.siliconObserved}</div></section>
<section class="panel"><h2>设计流程与当前状态</h2><p>Stage A → 规划候选 → Stage B 算子估算 → <b class="bad">Q-Gate 阻塞</b> → Stage A 反馈</p><code>${esc(detail.performanceAcceptance.status)}</code><p>可比槽位未达 ${detail.performanceAcceptance.targetTpsPerUser}：${detail.performanceAcceptance.comparableSlotsBelowTarget} / ${detail.performanceAcceptance.comparableSlotCount}（正式候选达标是入选规则的要求，不是性能结论）。${(detail.performanceAcceptance.selectedTauConditions||[]).map(x=>`<code>${esc(x.candidateId)}</code> 仅在 τ ≤ ${x.maxTauUsForTarget===null?'—':x.maxTauUsForTarget.toFixed(2)} μs 时三模型均达标${x.tauConditional?'（τ 条件候选）':''}`).join('；')}</p><p>算子记录 ${detail.operatorLedger.length} · 合成事件 ${detail.operatorLedger.length*4} · sweep ${sweep.sampleCount} 点 / 达标 ${sweep.feasibleCount}（${esc(sweep.summary.scope)}）· 运行模式 <code>${esc(detail.runMode)}</code>。</p></section>
<section class="grid"><div class="panel"><h2>D-Gate 检查</h2><table>${checks(gate.directionGate)}</table></div><div class="panel"><h2>Q-Gate 检查</h2><table>${checks(gate.quantificationGate)}</table></div></section>
<section class="panel"><h2>18 槽位规划估算 · 不是实测 TPS</h2><p class="muted">规划 token 时间 = max(访存道, 串行道) × 1.17；访存道 = kMemory ${cal.kMemory.toFixed(4)} ×（字节 + 专家重读 ${cal.expertReread.toFixed(2)} × routed 字节）/ 带宽；串行道 = kFlop ${cal.kFlop.toFixed(4)} × FLOP 时间 + 每层固定 ${cal.fixedPerLayerUs.toFixed(3)} μs × 层数 + 暴露 TMA ${cal.kTmaExposedUsPerGB.toFixed(2)} μs/GB + 集合通信次数 × τ（ADR-0008）。各系数只在 K3 详细模型 MC640 发布点的时间分解上标定（详细模型 MC320 / MC640 为 ${historicalK3} TPS；MC320 为样本外核对，规划/详细 = ${detail.tokenTime.calibration.validation.planningOverDetailed.toFixed(3)}），未经事件时序验证。K3 算子来自 design_engine 工程 preset；DeepSeek-V4-Pro 由 manifest shape 推导，含显式 ASSUMPTION；GLM-5.2 由公开 config.json 推导（78 层、21 个 full indexer 层），KV/索引键字节与每层集合通信次数为 ASSUMPTION。</p><p class="muted">τ 区间列为 τ = ${cal.tauSensitivityUs.join(' / ')} μs 下的 TPS/usr 区间（点估计取 ${cal.tauUs} μs，候选入选只看点估计；区间是风险提示，不是入选依据；B-008 关闭前 TP32 槽位须同时看区间）；形状区间列为 DeepSeek-V4-Pro 专家 hidden 按 49B 激活与按 1.6T 总参两种解法的区间。</p><table><thead><tr><th>模型</th><th>TP</th><th>MC</th><th>Profile</th><th>规划 TPS（τ=${cal.tauUs}）</th><th>τ 区间</th><th>形状区间</th><th>瓶颈算子</th><th>证据状态</th></tr></thead><tbody>${rows}</tbody></table><h2>权重 dtype 口径</h2><table><thead><tr><th>模型</th><th>attention / dense 投影</th><th>shared 专家</th><th>router / LM head</th><th>routed 专家</th><th>KV</th></tr></thead><tbody>${dtypeRows}</tbody></table></section>
<section class="panel"><h2>三团队 Contract 状态</h2><table><tr><th>团队</th><th>状态</th><th>关键阻塞</th></tr><tr><td>Model Team</td><td class="bad">${esc(modelContract.status)}</td><td>${esc(modelContract.blockers.join('; '))}</td></tr><tr><td>Hardware Team</td><td class="bad">${esc(hardwareContract.status)}</td><td>${esc(hardwareContract.blockers.join('; '))}</td></tr><tr><td>Software Team</td><td class="bad">${esc(softwareContract.status)}</td><td>${esc(softwareContract.blockers.join('; '))}</td></tr><tr><td>Integration</td><td class="bad">${esc(integrationContract.status)}</td><td>${esc(integrationHashMessage)}</td></tr><tr><td>Timing Evidence</td><td class="bad">${esc(evidence.current)}</td><td>validated slots: ${evidence.validatedSlots}; Q-Gate: ${evidence.qGate}</td></tr></table></section><section class="panel"><h2>剩余阻塞与责任 Agent</h2><table><tr><th>优先级 / Agent</th><th>阻塞</th><th>验收条件</th></tr>${blockers.map(x=>`<tr><td>${esc(x.priority+' / '+x.id)}</td><td>${esc(x.issue)}</td><td>${esc(x.exit)}</td></tr>`).join('')}</table></section>
<section class="panel"><h2>文档和机器产物</h2><ul>${[...sources,'out/governance/direction_feedback.json','teams/council/adr/ADR-0003-planning-evidence-boundary.md',IDS.stageAReport,IDS.stageBReport,'out/workload/planning_operator_workload.json','out/contracts/model_workload_contract.json','out/contracts/hardware_resource_contract.json','out/contracts/software_execution_contract.json','out/contracts/integration_manifest.json','out/verification/timing_evidence_status.json'].map(p=>`<li><a href="../../${esc(p)}">${esc(p)}</a></li>`).join('')}</ul><p>刷新：<code>npm run dashboard</code>；验证：<code>npm test</code>。本页不声明远端 CI 已通过。</p></section>
<script id="dashboard-source-hashes" type="application/json">${JSON.stringify(hashes)}</script></main></body></html>`;
fs.writeFileSync(path.join(root,'out/dashboard/architecture_global_dashboard.html'),html+'\n');
console.log('Generated dashboard from current artifacts');
